# Generated by Django 3.0 on 2023-03-31 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot_command',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
